services:
  - type: web
    name: truck-tracking-api
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: daphne -b 0.0.0.0 -p $PORT truck_tracking.asgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: truck-tracking-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False

databases:
  - name: truck-tracking-db
    databaseName: truck_tracking
    user: truck_tracking_user
