# Generated by Django 4.2.7 on 2025-09-25 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='capacity_tons',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='truck',
            name='truck_type',
            field=models.CharField(choices=[('mini', 'Mini Truck'), ('small', 'Small Truck'), ('medium', 'Medium Truck'), ('large', 'Large Truck'), ('heavy', 'Heavy Truck')], default='small', max_length=15),
        ),
        migrations.CreateModel(
            name='RouteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_location', models.CharField(max_length=200)),
                ('end_location', models.CharField(max_length=200)),
                ('start_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('start_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('end_latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('end_longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('material_type', models.CharField(choices=[('general', 'General Cargo'), ('oil', 'Oil & Petroleum'), ('gas', 'Gas'), ('chemical', 'Chemical'), ('food', 'Food Items'), ('construction', 'Construction Materials'), ('electronics', 'Electronics'), ('textiles', 'Textiles'), ('machinery', 'Machinery'), ('other', 'Other')], default='general', max_length=20)),
                ('required_truck_type', models.CharField(choices=[('mini', 'Mini Truck'), ('small', 'Small Truck'), ('medium', 'Medium Truck'), ('large', 'Large Truck'), ('heavy', 'Heavy Truck'), ('any', 'Any Type')], default='any', max_length=15)),
                ('estimated_weight_tons', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('budget_min', models.DecimalField(decimal_places=2, help_text='Minimum budget in INR', max_digits=10)),
                ('budget_max', models.DecimalField(decimal_places=2, help_text='Maximum budget in INR', max_digits=10)),
                ('pickup_deadline', models.DateTimeField(help_text='Latest pickup time')),
                ('delivery_deadline', models.DateTimeField(help_text='Required delivery time')),
                ('status', models.CharField(choices=[('open', 'Open for Bidding'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=15)),
                ('winning_bid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_routes', to=settings.AUTH_USER_MODEL)),
                ('assigned_truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.truck')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'route_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, help_text='Bid amount in INR', max_digits=10)),
                ('estimated_pickup_time', models.DateTimeField()),
                ('estimated_delivery_time', models.DateTimeField()),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('route_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='tracking.routerequest')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.truck')),
            ],
            options={
                'db_table': 'route_bids',
                'ordering': ['bid_amount'],
                'unique_together': {('route_request', 'driver')},
            },
        ),
        migrations.AddField(
            model_name='deliveryroute',
            name='accepted_bid',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_route', to='tracking.routebid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryroute',
            name='route_request',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_route', to='tracking.routerequest'),
            preserve_default=False,
        ),
    ]
